version: '2'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - db
    env_file: .env
  db:
    image: postgres
    volumes:
      - .:/embedded-ctf-scoreboard-db
    restart: unless-stoppedx
